student_manager/student_manager/urls.py
# student_manager/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView
from accounts import views as accounts_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('about/', TemplateView.as_view(template_name='about.html'), name='about'),
    path('home/', login_required(TemplateView.as_view(template_name='home.html')), name='home'),
    path('attendance/',include('attendance.urls')),
    path('', accounts_views.redirect_to_about, name='redirect_to_about'),
    path('todo/', include('todo.urls')),
]

student_manager/todo/urls.py
# todo/urls.py
from django.urls import path
from . import views

app_name = 'todo'

urlpatterns = [
    path('', views.task_list, name='task_list'),
    path('add/', views.add_task, name='add_task'),
    path('update_status/<int:task_id>/<str:status>/', views.update_task_status, name='update_task_status'),
    path('uncompleted/', views.uncompleted_tasks, name='uncompleted_tasks'),
    path('in_progress/', views.in_progress_tasks, name='in_progress_tasks'),
    path('completed/', views.completed_tasks, name='completed_tasks'),
]

student_manager/todo/models.py
# todo/models.py
from django.db import models
from accounts.models import CustomUser

class Task(models.Model):
    STATUS_CHOICES = [
        ('U', 'Uncompleted'),
        ('P', 'In Progress'),
        ('F', 'Finished')
    ]

    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    status = models.CharField(max_length=1, choices=STATUS_CHOICES, default='U')
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

student_manager/todo/forms.py
# todo/forms.py
from django import forms
from .models import Task

class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['name']

student_manager/todo/views.py
# todo/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from .models import Task
from .forms import TaskForm

@login_required
def task_list(request):
    tasks = Task.objects.filter(user=request.user).exclude(status='F')
    return render(request, 'todo/task_list.html', {'tasks': tasks})

@login_required
def add_task(request):
    if request.method == 'POST':
        form = TaskForm(request.POST)
        if form.is_valid():
            task = form.save(commit=False)
            task.user = request.user
            task.save()
            return redirect('todo:task_list')
    else:
        form = TaskForm()
    return render(request, 'todo/add_task.html', {'form': form})

@login_required
def update_task_status(request, task_id, status):
    task = get_object_or_404(Task, id=task_id, user=request.user)
    task.status = status
    task.save()
    return redirect('todo:task_list')

@login_required
def uncompleted_tasks(request):
    tasks = Task.objects.filter(user=request.user, status='U')
    return render(request, 'todo/task_list.html', {'tasks': tasks})

@login_required
def in_progress_tasks(request):
    tasks = Task.objects.filter(user=request.user, status='P')
    return render(request, 'todo/task_list.html', {'tasks': tasks})

@login_required
def completed_tasks(request):
    tasks = Task.objects.filter(user=request.user, status='F')
    return render(request, 'todo/task_list.html', {'tasks': tasks})

student_manager/todo/templates/todo/add_task.html
<!-- templates/todo/add_task.html -->
{% extends 'todo/base.html' %}

{% block content %}
<h1>Add Task</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Add</button>
</form>
{% endblock %}

student_manager/todo/templates/todo/base.html
<!-- templates/todo/base.html -->
<!DOCTYPE html>
<html>
<head>
    <title>To-Do List</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'todo:task_list' %}">Tasks</a>
        <div class="collapse navbar-collapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'todo:uncompleted_tasks' %}">Uncompleted</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'todo:in_progress_tasks' %}">In Progress</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'todo:completed_tasks' %}">Completed</a>
                </li>
            </ul>
        </div>
    </nav>
    <div class="container mt-4">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

student_manager/todo/templates/todo/task_list.html
<!-- templates/todo/task_list.html -->
{% extends 'todo/base.html' %}

{% block content %}
<h1>Tasks</h1>
<ul class="list-group">
    {% for task in tasks %}
        <li class="list-group-item d-flex justify-content-between align-items-center">
            {{ task.name }}
            <div>
                <a href="{% url 'todo:update_task_status' task.id 'P' %}" class="btn btn-sm btn-warning">Started</a>
                <a href="{% url 'todo:update_task_status' task.id 'F' %}" class="btn btn-sm btn-success">Finished</a>
                <a href="{% url 'todo:update_task_status' task.id 'D' %}" class="btn btn-sm btn-danger">Delete</a>
            </div>
        </li>
    {% endfor %}
</ul>
<a href="{% url 'todo:add_task' %}" class="btn btn-primary mt-3">Add Task</a>
{% endblock %}